---
config:
  layer_z_step: 1.0  # unit separation between layers
  mesh_edge_break_ratio: 0.5
  mesh_layer_offset: 0.0
  collapse_layers: false
  places_colormap_min_distance: 0.0
  places_colormap_max_distance: 3.0
  places_colormap:
    min_hue: 0.0
    max_hue: 0.5
    min_saturation: 0.9
    max_saturation: 0.8
    min_luminance: 0.6
    max_luminance: 0.85
  dynamic_layers:
    '2':
      visualize: true
      num_colors: 5
      saturation: 0.9
      luminance: 0.7
      edge_sl_ratio: 0.6
      node_scale: 0.1
      node_alpha: 0.65
      node_use_sphere: true
      edge_scale: 0.05
      edge_alpha: 0.8
      label_height: 0.5
      label_scale: 0.4
      color_offset: 3
      interlayer_edge_insertion_skip: 10
      visualize_interlayer_edges: false
      z_offset_scale: 0.0
  layer1:
    visualize: false
  layer2:
    visualize: false
  layer3:
    z_offset_scale: -0.8
    visualize: true
    # nodes
    marker_scale: 0.05
    marker_color_mode: 2  # parent
    marker_alpha: 0.5
    use_sphere_marker: true
    use_label: false
    use_bounding_box: false
    # edges
    use_edge_source: false
    intralayer_edge_scale: 0.001
  layer4:
    # general
    z_offset_scale: 2.0
    visualize: true
    # nodes
    marker_scale: 0.8
    marker_color_mode: 0  # default
    marker_alpha: 1.0
    use_sphere_marker: false
    use_label: false
    use_collapsed_label: false
    label_height: 1.25
    label_scale: 0.5
    use_bounding_box: false
    # edges
    use_edge_source: true
    intralayer_edge_scale: 0.08
    intralayer_edge_alpha: 1.0
    interlayer_edge_scale: 0.02
    interlayer_edge_alpha: 0.4
    interlayer_edge_use_color: true
    interlayer_edge_insertion_skip: 0
  layer5:
    visualize: false
llm_plugins:
  dsg_mesh: MeshPlugin
  places_footprints: FootprintPlugin
dsg_mesh:
  label_colormap: ''
  color_by_label: false
llm_places:
  min_score: 0.58
  max_score: 0.65
color_objects_by_task: true
color_places_by_task: false
color_rooms_by_task: false
places_footprints:
  use_place_radius: false
  num_samples: 50
  draw_boundary_vertices: true
  line_width: 0.02
  z_offset: -0.8
  color:
    type: ParentColorAdaptor
