#!/usr/bin/env python3
"""Script to generate a qualitative color map."""
import distinctipy
import click
import pathlib


def _get_output_path(name):
    return pathlib.Path(__file__).absolute().parent.parent / "config" / f"{name}.csv"


@click.command()
@click.option("--num-colors", "-n", default=40, help="number of colors")
@click.option("--pastel-factor", "-p", default=0.2, help="pastel factor")
@click.option("--seed", "-s", default=1234, help="random seed")
@click.option("--name", "-n", default="task_colors", help="filename")
def main(num_colors, pastel_factor, seed, name):
    """Generate a color palette."""
    colors = distinctipy.get_colors(num_colors, pastel_factor=pastel_factor, rng=seed)
    output_path = _get_output_path(name)
    click.secho(f"writing {num_colors} to '{output_path}'")
    with output_path.open("w") as fout:
        fout.write("name,red,green,blue,alpha,id\n")
        for i, color in enumerate(colors):
            r = int(255 * color[0])
            g = int(255 * color[1])
            b = int(255 * color[2])
            fout.write(f"task_{i},{r},{g},{b},255,{i}\n")


if __name__ == "__main__":
    main()
