---
globals:
  max_range: &max_range $(arg sensor_max_range)  # m
  temporal_window: &temporal_window 3.0  # s
map_window:
  type: spatial
  max_radius_m: 8.0
active_window:
  type: ActiveWindow
  verbosity: 2
  min_output_separation: 0.0
  volumetric_map:
    voxel_size: 0.1
    truncation_distance: 0.3
    voxels_per_side: 16
    with_semantics: true
  frame_data_buffer:
    max_buffer_size: 300
    store_every_n_frames: 1
  motion_detector:
    type: FreeSpaceMotionDetector
    min_cluster_size: 500
    min_separation_distance: 2
    max_range: *max_range
  object_detector:
    type: ConnectedSemantics
    min_cluster_size: 50
    use_full_connectivity: true
    use_3d: true
    grid_size: 0.1
    max_range: *max_range
  tracker:
    type: MaxIouTracker
    track_by: voxels
    min_semantic_iou: 0.25
    min_cross_iou: 0.1
    voxel_size: 0.2
    temporal_window: *temporal_window
    min_num_observations: 15
  projective_integrator:
    interpolation_method: bilinear
  tracking_integrator:
    temporal_window: *temporal_window
  object_extractor:
    type: MeshObjectExtractor
    verbosity: 1
    min_object_allocation_confidence: 0.5
    min_object_volume: 0.005
    max_object_volume: 10.0
    min_dynamic_displacement: 1
    only_extract_reconstructed_objects: true
    min_object_reconstruction_confidence: 0.5
    min_object_reconstruction_observations: 0
    object_reconstruction_resolution: -0.02
    projective_integrator:
      num_threads: 2  # NOTE(lschmid): Test less threads for parallel object extraction.
      semantic_integrator:
        type: BinarySemanticIntegrator
frontend:
  type: GraphBuilder
  pgmo:
    time_horizon: 15.0
    d_graph_resolution: 2.5
    mesh_resolution: 0.005
  graph_updater:
    layer_updates:
      objects: {prefix: o}
  enable_mesh_objects: false
  surface_places:
    type: place_2d
    prefix: P
    pure_final_place_size: 1
    cluster_tolerance: .3
    min_cluster_size: 50
    max_cluster_size: 100000
    min_final_place_points: 10
    place_max_neighbor_z_diff: .5
    place_overlap_threshold: 0.0
  freespace_places:
    type: gvd
    filter_places: true
    min_places_component_size: 3
    filter_ground: false
    gvd:
      max_distance_m: 4.5
      min_distance_m: 0.2
      min_diff_m: 0.1
      voronoi_config:
        mode: L1_THEN_ANGLE
        min_distance_m: 0.30
        parent_l1_separation: 20
        parent_cos_angle_separation: 0.2
    graph:
      type: CompressionGraphExtractor
      compression_distance_m: 1.5
      min_node_distance_m: 0.4
      min_edge_distance_m: 0.25
      node_merge_distance_m: 0.7
      merge_policy: distance
    tsdf_interpolator:
      type: downsample
      ratio: 2
  use_frontiers: false
  frontier_places:
    type: voxel_clustering
    cluster_tolerance: 0.3
    min_cluster_size: 10
    max_cluster_size: 100000
    max_place_radius: 5
    dense_frontiers: false
    frontier_splitting_threshold: 0.2
    point_threshold: 10
    recent_block_distance: 25
    minimum_relative_z: -1.
    maximum_relative_z: 1
backend:
  type: BackendModule
  add_places_to_deformation_graph: true
  optimize_on_lc: true
  enable_node_merging: true
  update_functors:
    agents:
      type: UpdateAgentsFunctor
    objects:
      type: UpdateObjectsFunctor
    surface_places:
      type: Update2dPlacesFunctor
    places:
      type: UpdatePlacesFunctor
    frontiers:
      type: UpdateFrontiersFunctor
    rooms:
      type: UpdateRoomsFunctor
      room_finder:
        min_dilation_m: 0.5
        max_dilation_m: 1.2
        min_component_size: 10
        min_room_size: 10
        dilation_threshold_mode: PLATEAU
        min_lifetime_length_m: 0.1
        plateau_ratio: 0.15
        clustering_mode: NEIGHBORS
        dilation_diff_threshold_m: -1.0
    buildings:
      type: UpdateBuildingsFunctor
    zmq_labels:
      type: ZmqRoomLabelUpdater
  pgmo:
    run_mode: FULL  # kimera_pgmo run mode FULL is required
    embed_trajectory_delta_t: 5.0
    num_interp_pts: 3
    interp_horizon: 10.0
    enable_sparsify: false
    trans_node_dist: 1.0
    rot_node_dist: 1.2
    rpgo:
      odom_trans_threshold: 0.05
      odom_rot_threshold: 0.01
      pcm_trans_threshold: -1
      pcm_rot_threshold: -1
      lm_diagonal_damping: true
      gnc_alpha: 0.9
      gnc_max_iterations: 100
      gnc_mu_step: 1.6
      gnc_cost_tolerance: 1.0e-05
      gnc_weight_tolerance: 1.0e-04
      gnc_fix_prev_inliers: true
      verbosity: UPDATE
      solver: LM
    add_initial_prior: true
    covariance:
      odom: 1.0e-02
      loop_close: 5.0e-02
      sg_loop_close: 1.0e-01
      prior: 1.0e-02
      mesh_mesh: 1.0e-02
      pose_mesh: 1.0e-02
      place_mesh: 1.0e-02
      place_edge: 10.0
      place_merge: 10.0
      object_merge: 10.0
