---
type: BackendModule
dsg:
  places_merge_distance_tolerance_m: 0.4
pgmo:
  run_mode: 0    # kimera_pgmo run mode FULL (required)
  use_msg_time: true
  embed_trajectory_delta_t: 5.0
  num_interp_pts: 3
  interp_horizon: 10.0
  enable_sparsify: false
  trans_node_dist: 1.0
  rot_node_dist: 1.2
  rpgo:
    odom_trans_threshold: 0.05
    odom_rot_threshold: 0.01
    pcm_trans_threshold: -1
    pcm_rot_threshold: -1
    gnc_alpha: 0.9
    gnc_mu_step: 1.6
    gnc_fix_prev_inliers: true
    verbosity: UPDATE
    solver: LM
  covariance:
    odom: 1.0e-02
    loop_close: 5.0e-02
    sg_loop_close: 1.0e-01
    prior: 1.0e-02
    mesh_mesh: 1.0e-02
    pose_mesh: 1.0e-02
    place_mesh: 1.0e-02
    place_edge: 10.0
    place_merge: 10.0
    object_merge: 10.0
enable_rooms: false
regions:
  extractor:
    type: PlaceClustering
    min_assocation_iou: 0.8
    clustering:
      type: $(arg places_clustering_type)
      stop_value: 0.0
      tasks:
        type: RosTaskEmbeddings
      norm:
        type: cosine
      merge:
        type: weighted_mean
