---
graphs:
  clustering:
    plugins:
      segments: LLMLayerPlugin
      objects: LLMLayerPlugin
      places: LLMLayerPlugin
      regions: LLMLayerPlugin
      interlayer_edges: InterlayerPlugin
      dsg_mesh: MeshPlugin
gt_publisher:
  filepath: $(arg gt_path)
  scale: 0.05
  tasks:
    colormap_filepath: $(arg semantic_colormap)
    task_service_name: /gt_task_server/get_embedding
clustering:
  interlayer_edges:
    skiplist: [5]
  segments:
    layer: 1
    layer_to_use: 1
    visualization_layer: 1
    min_saturation:  0.5
  objects:
    layer: 2
    layer_to_use: 2
    visualization_layer: 2
    min_saturation: 0.5
  places:
    layer: 3
    layer_to_use: 3
    visualization_layer: 3
    min_saturation:  0.5
  regions:
    layer: 4
    layer_to_use: 4
    visualization_layer: 4
    min_saturation:  0.5
  config:
    layer1:
      visualize: true
      z_offset_scale: 1.5
      marker_scale: 0.05
      use_bounding_box: true
      use_sphere_marker: true
      collapse_bounding_box: false
      bbox_wireframe_scale: 0.02
      bbox_wireframe_edge_scale: 0.02
    layer2:
      visualize: true
      z_offset_scale: 0.5
      marker_scale: 0.3
      use_label: true
      label_scale: 0.25
      use_bounding_box: true
      collapse_bounding_box: true
      bbox_wireframe_scale: 0.02
      bbox_wireframe_edge_scale: 0.02
      interlayer_edge_scale: 0.01
      interlayer_edge_alpha: 0.6
    layer3:
      visualize: true
      z_offset_scale: 2.5
      marker_scale: 0.2
      use_label: false
      use_bounding_box: false
      interlayer_edge_scale: 0.01
      interlayer_edge_alpha: 0.6
    layer4:
      visualize: true
      z_offset_scale: 3.5
      marker_scale: 0.3
      use_label: true
      use_bounding_box: false
      interlayer_edge_scale: 0.01
      interlayer_edge_alpha: 0.6
