---
#############################
#  Input Module Parameters  #
#############################
label_info:
  type: $(arg label_type)
  label_file: $(arg object_label_file)
inputs:
  - ns: input1
    sensor:
      type: camera_info
      min_range: $(arg sensor_min_range)
      max_range: $(arg sensor_max_range)
      camera_info_topic: $(arg input1/rgb_info_topic)
      extrinsics:
        type: ros
        sensor_frame: $(arg sensor1_frame)
  - ns: input2
    sensor:
      type: camera_info
      min_range: $(arg sensor_min_range)
      max_range: $(arg sensor_max_range)
      camera_info_topic: $(arg input2/rgb_info_topic)
      extrinsics:
        type: ros
        sensor_frame: $(arg sensor2_frame)
input1:
  global_frame_name: $(arg odom_frame)
  sensor_frame_name: $(arg sensor1_frame)
  subscriber:
    type: $(arg subscriber_type)
    input_images_are_const: false
    color_image_topic: color/image_raw
    depth_image_topic: depth/image_rect
    semantic_image_topic: semantic/image_raw
    queue_size: 100
input2:
  global_frame_name: $(arg odom_frame)
  sensor_frame_name: $(arg sensor2_frame)
  subscriber:
    type: $(arg subscriber_type)
    input_images_are_const: false
    color_image_topic: color/image_raw
    depth_image_topic: depth/image_rect
    semantic_image_topic: semantic/image_raw
    queue_size: 100
#############################################
#  Active-Window Reconstruction Parameters  #
#############################################
reconstruction:
  use_visualizer: true
  sinks:
    - {type: TsdfOccupancyPublisher, extraction: {min_distance: 0.25}}
  active_window_viz:
    color_mode: color
    global_frame_name: $(arg odom_frame)
    slice_height: -0.5
    slice_height_is_relative: true
    activity_shading_intensity: 0.6
    object_color_mode: 0
  active_window:  # taken from Khronos
    verbosity: 1
    find_visible_blocks_accurately: false
    max_frame_data_buffer_size: 300
    store_every_n_frame_data: 1
    min_object_allocation_confidence: 0.5
    min_object_volume: 0.0  # m^3
    min_object_reconstruction_confidence: 0.5
    scale_object_reconstruction_confidence_with_weight: true
    min_object_reconstruction_observations: 5
    object_reconstruction_resolution: -0.1  # Positive: voxel size in meters. Negative: fraction of the extent. 0: Skip. (-0.02)
    volumetric_map:
      voxel_size: 0.1  # m
      truncation_distance: 0.3  # m (Usually 2-3x voxel size)
      voxels_per_side: 16
    object_detector:
      type: $(arg object_detection_type)   # 'connected_semantics' 'instance_forwarding'
      min_cluster_size: 100  # pixels
      use_full_connectivity: true
      use_3d: true
      grid_size: 0.1  # m
      max_range: $(arg sensor_max_range)
    tracker:
      type: max_iou   # 'max_iou'
      track_by: voxels   # 'pixels', 'voxels', 'bounding_box'
      min_semantic_iou: 0.25
      min_cosine_sim: -1.0
      min_cross_iou: 0.1
      temporal_window: $(arg temporal_window_size_s)
      min_num_observations: 30
    projective_integrator:
      max_weight: 100000
      interpolation_method: adaptive   # "nearest", "bilinear", "adaptive"
      verbosity: 1
    tracking_integrator:
      temporal_window: $(arg temporal_window_size_s)
      verbosity: 1
    robot_footprint:
      type: RobotFootprintIntegrator
      bbox_min: [-0.5, -0.15, -0.1]
      bbox_max: [0.5, 0.15, 0.1]
      tsdf_weight: 1.0e-4
#########################
#  Frontend Parameters  #
#########################
frontend:
  type: LLMFrontend
  pgmo:
    horizon: 15.0
    d_graph_resolution: 2.5
    output_mesh_resolution: 0.005
  min_object_vertices: 0
  min_object_score: 0.2
  prune_mesh_indices: true
  places:
    type: gvd
    gvd:
      max_distance_m: 4.5
      min_diff_m: 0.1
      min_basis_for_extraction: 1
      voronoi_config:
        min_distance_m: 0.30
        parent_l1_separation: 20
        parent_cos_angle_separation: 0.2
    graph:
      type: CompressionGraphExtractor
      compression_distance_m: 1.0
      min_node_distance_m: 0.4
      min_edge_distance_m: 0.25
      node_merge_distance_m: 0.5
      add_heuristic_edges: true
    sinks:
      - {type: GvdOccupancyPublisher, extraction: {min_distance: 0.25}}
########################
#  Backend Parameters  #
########################
backend:
  type: BackendModule
  dsg:
    places_merge_distance_tolerance_m: 0.4
  pgmo:
    run_mode: 0  # kimera_pgmo run mode FULL (required)
    use_msg_time: true
    embed_trajectory_delta_t: 5.0
    num_interp_pts: 3
    interp_horizon: 10.0
    enable_sparsify: false
    trans_node_dist: 1.0
    rot_node_dist: 1.2
    rpgo:
      odom_trans_threshold: 0.05
      odom_rot_threshold: 0.01
      pcm_trans_threshold: -1
      pcm_rot_threshold: -1
      gnc_alpha: 0.9
      gnc_mu_step: 1.6
      gnc_fix_prev_inliers: true
      verbosity: UPDATE
      solver: LM
    covariance:
      odom: 1.0e-02
      loop_close: 5.0e-02
      sg_loop_close: 1.0e-01
      prior: 1.0e-02
      mesh_mesh: 1.0e-02
      pose_mesh: 1.0e-02
      place_mesh: 1.0e-02
      place_edge: 10.0
      place_merge: 10.0
      object_merge: 10.0
  enable_rooms: false
  regions:
    extractor:
      type: PlaceClustering
      min_assocation_iou: 0.8
      clustering:
        type: $(arg places_clustering_type)
        stop_value: 0.0
        tasks:
          type: RosEmbeddingGroup
        metric:
          type: cosine
        merge:
          type: weighted_mean
#############################
#  ROS Argument Parameters  #
#############################
robot_id: $(arg robot_id)
odom_frame: $(arg odom_frame)
robot_frame: $(arg robot_frame)
map_frame: $(arg map_frame)
exit_after_clock: false
enable_frontend_output: true
semantic_colormap_file: $(arg semantic_map_path)
enable_lcd: $(arg enable_lcd)
log_path: $(arg log_path)
frontend/objects/bounding_box_type: AABB
frontend/validate_vertices: false
backend/dsg/optimize_on_lc: true
backend/dsg/enable_merge_undos: false
backend/dsg/use_zmq_interface: false
loop_closure/type: LoopClosureModule
loop_closure/detector/agent/descriptors/vocabulary_path: $(arg vocabulary_path)
